# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy Website

on:
  push:
   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Installing Node 
      uses: actions/setup-node@v2-beta
      with: 
        node-version: 12
    - name: Installing surge 
      run: npm install --global surge
    - name: deploying using surge
      run: surge ./http:/ itzone.surge.sh --token ${{ secrets.SURGE_TOKEN }} 
      
